development:
  adapter: postgresql
  database: livingbull_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: livingbull_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: livingbull_production
  pool: 5